"""Domain layer: framework-free entities, enums, ports and errors."""

from lecture_transcriber.domain.enums import (
    ALLOWED_TRANSITIONS,
    TERMINAL_STATUSES,
    ErrorCode,
    JobStatus,
    MediaType,
    WarningCode,
)
from lecture_transcriber.domain.errors import (
    AsrFailed,
    DomainError,
    ExportFailed,
    InvalidOptions,
    InvalidStateTransition,
    JobCancelled,
    JobLeaseLost,
    MediaError,
    MediaProbeFailed,
    MediaTooLarge,
    ModelLoadFailed,
    ModelNotAvailable,
    UnsupportedFormat,
)
from lecture_transcriber.domain.models import (
    Artifact,
    EngineMetadata,
    HardwareFacts,
    HardwareProfile,
    JobEvent,
    LanguageMetadata,
    Media,
    Transcript,
    TranscriptionJob,
    TranscriptionOptions,
    TranscriptSegment,
    TranscriptWarning,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "TERMINAL_STATUSES",
    "Artifact",
    "AsrFailed",
    "DomainError",
    "EngineMetadata",
    "ErrorCode",
    "ExportFailed",
    "HardwareFacts",
    "HardwareProfile",
    "InvalidOptions",
    "InvalidStateTransition",
    "JobCancelled",
    "JobEvent",
    "JobLeaseLost",
    "JobStatus",
    "LanguageMetadata",
    "Media",
    "MediaError",
    "MediaProbeFailed",
    "MediaTooLarge",
    "MediaType",
    "ModelLoadFailed",
    "ModelNotAvailable",
    "Transcript",
    "TranscriptSegment",
    "TranscriptWarning",
    "TranscriptionJob",
    "TranscriptionOptions",
    "UnsupportedFormat",
    "WarningCode",
]
